export const projects = [
  {
    id: 1,
    slug: "afridapay",
    title: "Afridapay – Payment & Financial Services Platform",
    description:
      "A modern payment and financial services platform based in Madagascar, offering card payments, QR-code payments, electronic wallets and fintech integrations for institutions and individuals.",
    thumbnail: "/projects/afridapay/thumb.png",
    screenshots: [
      "/projects/afridapay/1.png",
      "/projects/afridapay/2.png",
      "/projects/afridapay/3.png",
      "/projects/afridapay/4.png",
    ],
    link: "https://afridapay.com",
    tags: ["wordpress", "elementor"],
    category: "Fintech Platform",
    status: "Completed",
    created: "2024-05-10",
    updated: "2025-04",
    contributors: 3,
    views: 5000,
    progress: 100,
    funFact:
      "Afridapay offers payment solutions even for electric bus services in Madagascar using cards and QR codes.",
    features: [
      "Custom WordPress site built with Elementor for high flexibility",
      "Responsive design optimized for mobile and desktop",
      "Content management via WordPress CMS for easy updates by non‑technical staff",
      "SEO optimization to improve search engine rankings and visibility",
    ],
  },

  {
    id: 2,
    slug: "grand-hotel-urban",
    title: "Grand Hôtel Urban – Official Website of a Hotel in Antananarivo",
    description:
      "Website redesign for a boutique urban-hotel in Antananarivo, covering UI/UX design, CMS integration, fully responsive set-up and SEO optimization.",
    thumbnail: "/projects/grand-hotel-urban/thumb.png",
    screenshots: [
      "/projects/grand-hotel-urban/1.png",
      "/projects/grand-hotel-urban/2.png",
      "/projects/grand-hotel-urban/3.png",
    ],
    link: "https://ghu-tana.com/en",
    tags: [
      "React.js",
      "Tailwind CSS",
      "Javascript",
      "Express.js",
      "MySQL",
      "Node.js",
      "Socket.io",
    ],
    category: "Website / Web Development",
    status: "Completed",
    created: "2025-08-18",
    updated: "2025-08-18",
    contributors: 3,
    views: 0,
    progress: 100,
    funFact:
      "The hotel is located on a hill in the heart of Antananarivo and features a rooftop terrace with panoramic city views.",
    features: [
      "Secure admin interface",
      "Image gallery and virtual tour",
      "Booking form with payment API integration",
      "Mobile-first optimization & load time < 2s",
      "Multilingual (FR/EN)",
    ],
  },

  {
    id: 3,
    slug: "minucia",
    title: "Minucia – Corporate Website for Communication Agency",
    description:
      "A professional Next.js website built for Minucia, a communication agency based in Antananarivo, Madagascar, offering web development, graphic design, and branding services.",
    thumbnail: "/projects/minucia/thumb.png",
    screenshots: [
      "/projects/minucia/1.png",
      "/projects/minucia/2.png",
      "/projects/minucia/3.png",
      "/projects/minucia/4.png",
    ],
    link: "https://minucia-website.vercel.app/",
    tags: ["Next.js", "Typescript", "Tailwind CSS", "Firebase", "Figma"],
    category: "Website / Web Development",
    status: "In progress",
    created: "2025-06-17",
    updated: "2025-06-17",
    contributors: 4,
    views: 3200,
    progress: 75,
    funFact:
      "Minucia is based in Antananarivo and also offers remote services for clients abroad, including web development and branding. " /* tu peux adapter selon la réalité */,
    features: [
      "Built with Next.js for fast server-side rendering and scalability",
      "SEO‑optimized pages with meta tags, clean URL structure, and sitemap",
      "Responsive design optimized for mobile, tablet, and desktop",
      "Secure contact and project inquiry forms with spam protection",
      "Blog / News section for sharing agency updates, design insights, and case studies",
    ],
  },

  {
    id: 4,
    slug: "eden-distribution",
    title: "Eden Distribution – FMCG Distributor in Madagascar",
    description:
      "Eden Distribution is a Madagascan company specializing in the supply of a wide range of fast-moving consumer goods (FMCG) to the market.",
    thumbnail: "/projects/eden-distribution/thumb.png",
    screenshots: [
      "/projects/eden-distribution/1.png",
      "/projects/eden-distribution/2.png",
      "/projects/eden-distribution/3.png",
      "/projects/eden-distribution/4.png",
      "/projects/eden-distribution/5.png",
    ],
    link: "https://edens.mg",
    tags: ["Next.js", "Tailwind CSS", "Typescript", "Framer Motion"],
    category: "Website / Distribution Company",
    status: "Live",
    created: "2025-11-28",
    updated: "2025-11-28",
    contributors: 1,
    views: 0,
    progress: 100,
    funFact:
      "Eden Distribution employs around 100 people and runs distribution centers in Antananarivo and Toamasina, with a planned expansion to Réunion.",
    features: [
      "Online catalogue of FMCG products",
      "Distribution centers in Antananarivo and Toamasina",
      "Plan for expansion to Réunion",
      "Contact form / customer inquiries",
      "Customer testimonials and reviews",
    ],
  },

  {
    id: 5,
    slug: "tombola-manager",
    title: "Tombola Manager – Automated Raffle Application",
    description:
      "A full-stack Next.js application designed to manage company raffles with two separate interfaces (admin and client). Includes separate authentication systems (admin token), Firebase data storage, automated Facebook draw announcements via n8n, Docker containerization, and Jest unit testing. The goal is to provide a simple, accessible (responsive + a11y), and robust experience for managing automated raffle draws.",
    thumbnail: "/projects/tombola-manager/thumb.png",
    screenshots: [
      "/projects/tombola-manager/1.png",
      "/projects/tombola-manager/2.png",
      "/projects/tombola-manager/3.png",
      "/projects/tombola-manager/4.png",
      "/projects/tombola-manager/5.png",
      "/projects/tombola-manager/6.png",
      "/projects/tombola-manager/7.png",
      "/projects/tombola-manager/8.png",
      "/projects/tombola-manager/9.png",
    ],
    link: "https://tombola.edens.mg",
    tags: [
      "Next.js",
      "Tailwind CSS",
      "Typescript",
      "Firebase",
      "Docker",
      "n8n",
      "Jest",
    ],
    category: "Application / Raffle System",
    status: "Completed",
    created: "2025-11-28",
    updated: "2025-11-28",
    contributors: 1,
    views: 0,
    progress: 100,
    funFact:
      "The draw results are automatically posted to Facebook using n8n, with a clean separation between admin and client accounts for enhanced security.",
    features: [
      "Admin dashboard: draw management, participants, automation, and settings",
      "Client interface: ticket purchase, participation, and draw viewing",
      "Separated authentication (admin token) with role management",
      "Firebase-based data storage and real-time sync",
      "Automated Facebook draw announcements via n8n",
      "Docker containerization for reproducible deployments",
      "Jest unit testing to ensure robustness",
      "Responsive design and adherence to accessibility best practices",
      "Simple UX with transparent draw processes",
    ],
  },

  // {
  //   id: 14,
  //   slug: "sidata",
  //   title: "SIDATA - Family Data Information System for South Tangerang",
  //   description:
  //     "A web application for managing family data, population statistics, and data request services in South Tangerang City.",
  //   thumbnail: "/projects/sidata/thumb.png",
  //   screenshots: [
  //     "/projects/sidata/1.png",
  //     "/projects/sidata/2.png",
  //     "/projects/sidata/3.png",
  //     "/projects/sidata/4.png",
  //     "/projects/sidata/5.png",
  //     "/projects/sidata/6.png",
  //     "/projects/sidata/7.png",
  //     "/projects/sidata/8.png",
  //     "/projects/sidata/9.png",
  //   ],
  //   link: "https://sidata.tangsel.go.id",
  //   tags: ["React.js", "Tailwind CSS", "Typescript", "Express.js", "MySQL"],
  //   category: "Information System",
  //   status: "In Progress",
  //   created: "2025-03-26",
  //   updated: "2025-06-20",
  //   contributors: 3,
  //   views: 2345,
  //   progress: 90,
  //   funFact:
  //     "SIDATA is an internship project assigned by the mayor of South Tangerang.",
  //   features: [
  //     "Real-time population statistics",
  //     "Public data access via QR Code",
  //     "Interactive dashboard",
  //     "Export data to Excel/PDF",
  //   ],
  // },

  // {
  //   id: 13,
  //   slug: "garmen",
  //   title: "GarmenTrack - Garment Factory Tracking & Inventory System",
  //   description:
  //     "A platform to monitor production processes, raw material stock, and goods delivery in garment/textile factories.",
  //   thumbnail: "/projects/garmen/thumb.png",
  //   screenshots: [
  //     "/projects/garmen/1.png",
  //     "/projects/garmen/2.png",
  //     "/projects/garmen/3.png",
  //     "/projects/garmen/4.png",
  //     "/projects/garmen/5.png",
  //     "/projects/garmen/6.png",
  //     "/projects/garmen/7.png",
  //   ],
  //   link: "https://garmen-track.com",
  //   tags: ["Laravel", "Tailwind CSS", "Postgres"],
  //   category: "Information System",
  //   status: "In Progress",
  //   created: "2025-06-20",
  //   updated: "2025-07-07",
  //   contributors: 12,
  //   views: 1890,
  //   progress: 100,
  //   funFact:
  //     "This project is a collaboration between Informatics students at the Indonesian Institute of Technology.",
  //   features: [
  //     "Production process tracking",
  //     "Raw material stock management",
  //     "Goods delivery reports",
  //     "Multi-branch system",
  //     "Multi-user roles",
  //   ],
  // },
  // {
  //   id: 12,
  //   slug: "forumkm",
  //   title: "ForUMKM - MSME Service Platform",
  //   description:
  //     "A web application to help MSME actors promote products, find partners, and access business training.",
  //   thumbnail: "/projects/forumkm/thumb.png",
  //   screenshots: [
  //     "/projects/forumkm/1.png",
  //     "/projects/forumkm/2.png",
  //     "/projects/forumkm/3.png",
  //     "/projects/forumkm/4.png",
  //   ],
  //   link: "https://forumkm.id",
  //   tags: ["Next.js", "Tailwind CSS", "Typescript"],
  //   category: "Web App",
  //   status: "On Hold",
  //   created: "2025-03-10",
  //   updated: "2025-04-10",
  //   contributors: 4,
  //   views: 3200,
  //   progress: 80,
  //   funFact:
  //     "This project is the result of collaboration between students of the Indonesian Institute of Technology.",
  //   features: [
  //     "MSME product marketplace",
  //     "Online training",
  //     "Payment integration",
  //   ],
  // },
  // {
  //   id: 11,
  //   slug: "darunnajah",
  //   title: "SIAKAD - Darunnajah Academic Information System",
  //   description:
  //     "Academic information system for managing student data, grades, attendance, and schedules at Darunnajah Islamic Boarding School.",
  //   thumbnail: "/projects/darunnajah/thumb.png",
  //   screenshots: [
  //     "/projects/darunnajah/1.png",
  //     "/projects/darunnajah/2.png",
  //     "/projects/darunnajah/3.png",
  //     "/projects/darunnajah/4.png",
  //   ],
  //   link: "https://siakad.darunnajah.sch.id",
  //   tags: ["Angular", "Bootstrap", "Typescript", "Postgres"],
  //   category: "Information System",
  //   status: "In Progress",
  //   created: "2025-04-10",
  //   updated: "2023-07-10",
  //   contributors: 9,
  //   views: 2100,
  //   progress: 80,
  //   funFact:
  //     "This project is a collaboration between Informatics students at the Indonesian Institute of Technology.",
  //   features: [
  //     "Student data management",
  //     "Input & recap grades",
  //     "Online attendance",
  //     "Digital report card printing",
  //     "Human resource management",
  //     "Student finance",
  //   ],
  // },
  // {
  //   id: 10,
  //   slug: "noir",
  //   title: "Noir - Social Media App",
  //   description:
  //     "A modern social media app with posting, comments, and dark mode features.",
  //   thumbnail: "/projects/noir/thumb.png",
  //   screenshots: [
  //     "/projects/noir/1.png",
  //     "/projects/noir/2.png",
  //     "/projects/noir/3.png",
  //     "/projects/noir/4.png",
  //     "/projects/noir/5.png",
  //     "/projects/noir/6.png",
  //   ],
  //   link: "https://noir-app.com",
  //   tags: ["Next.js", "Tailwind CSS", "Javascript", "Strapi"],
  //   category: "Web App",
  //   status: "Completed",
  //   created: "2023-02-01",
  //   updated: "2023-02-20",
  //   contributors: 1,
  //   views: 4100,
  //   progress: 100,
  //   funFact:
  //     "I created this app to deepen and implement my fullstack knowledge without searching the internet.",
  //   features: [
  //     "Post with caption, Like, & comment",
  //     "Interact with other users",
  //     "Users can reply to comments",
  //     "Profile customization",
  //     "Responsive UI",
  //   ],
  // },

  // {
  //   id: 4,
  //   slug: "21cleanshoes",
  //   title: "21Cleanshoes - Online Shoe Laundry",
  //   description:
  //     "A web application for ordering, tracking, and paying for shoe laundry online.",
  //   thumbnail: "/projects/21cleanshoes/thumb.png",
  //   screenshots: [
  //     "/projects/21cleanshoes/1.png",
  //     "/projects/21cleanshoes/2.png",
  //     "/projects/21cleanshoes/3.png",
  //     "/projects/21cleanshoes/4.png",
  //   ],
  //   link: "https://21cleanshoes.com",
  //   tags: ["Next.js", "Tailwind CSS", "Typescript", "Framer Motion"],
  //   category: "Web App",
  //   status: "On Hold",
  //   created: "2022-12-08",
  //   updated: "2023-12-20",
  //   contributors: 1,
  //   views: 900,
  //   progress: 80,
  //   funFact:
  //     "This was my first client project, for my own cousin who owns a shoe laundry business.",
  //   features: [
  //     "Order online via email/whatsapp",
  //     "Interactive UI",
  //     "Testimonials",
  //   ],
  // },
];
