export const projects = [
  {
    id: 1,
    slug: "afridapay",
    title: "Afridapay – Payment & Financial Services Platform",
    description:
      "A modern payment and financial services platform based in Madagascar, offering card payments, QR-code payments, electronic wallets and fintech integrations for institutions and individuals.",
    thumbnail: "/projects/afridapay/thumb.png",
    screenshots: [
      "/projects/afridapay/1.png",
      "/projects/afridapay/2.png",
      "/projects/afridapay/3.png",
      "/projects/afridapay/4.png",
    ],
    link: "https://afridapay.com",
    tags: ["wordpress", "elementor"],
    category: "Fintech Platform",
    status: "Completed",
    created: "2024-05-10",
    updated: "2025-04",
    contributors: 3,
    views: 5000,
    progress: 100,
    funFact:
      "Afridapay offers payment solutions even for electric bus services in Madagascar using cards and QR codes.",
    features: [
      "Custom WordPress site built with Elementor for high flexibility",
      "Responsive design optimized for mobile and desktop",
      "Content management via WordPress CMS for easy updates by non‑technical staff",
      "SEO optimization to improve search engine rankings and visibility",
    ],
  },

  {
    id: 2,
    slug: "grand-hotel-urban",
    title: "Grand Hôtel Urban – Official Website of a Hotel in Antananarivo",
    description:
      "Website redesign for a boutique urban-hotel in Antananarivo, covering UI/UX design, CMS integration, fully responsive set-up and SEO optimization.",
    thumbnail: "/projects/grand-hotel-urban/thumb.png",
    screenshots: [
      "/projects/grand-hotel-urban/1.png",
      "/projects/grand-hotel-urban/2.png",
      "/projects/grand-hotel-urban/3.png",
    ],
    link: "https://ghu-tana.com/en",
    tags: [
      "React.js",
      "Tailwind CSS",
      "Javascript",
      "Express.js",
      "MySQL",
      "Node.js",
      "Socket.io",
    ],
    category: "Website / Web Development",
    status: "Completed",
    created: "2025-08-18",
    updated: "2025-08-18",
    contributors: 3,
    views: 0,
    progress: 100,
    funFact:
      "The hotel is located on a hill in the heart of Antananarivo and features a rooftop terrace with panoramic city views.",
    features: [
      "Secure admin interface",
      "Image gallery and virtual tour",
      "Booking form with payment API integration",
      "Mobile-first optimization & load time < 2s",
      "Multilingual (FR/EN)",
    ],
  },

  {
    id: 3,
    slug: "minucia",
    title: "Minucia – Corporate Website for Communication Agency",
    description:
      "A professional Next.js website built for Minucia, a communication agency based in Antananarivo, Madagascar, offering web development, graphic design, and branding services.",
    thumbnail: "/projects/minucia/thumb.png",
    screenshots: [
      "/projects/minucia/1.png",
      "/projects/minucia/2.png",
      "/projects/minucia/3.png",
      "/projects/minucia/4.png",
    ],
    link: "https://minucia-website.vercel.app/",
    tags: ["Next.js", "Typescript", "Tailwind CSS", "Firebase", "Figma"],
    category: "Website / Web Development",
    status: "In progress",
    created: "2025-06-17",
    updated: "2025-06-17",
    contributors: 4,
    views: 3200,
    progress: 75,
    funFact:
      "Minucia is based in Antananarivo and also offers remote services for clients abroad, including web development and branding. " /* tu peux adapter selon la réalité */,
    features: [
      "Built with Next.js for fast server-side rendering and scalability",
      "SEO‑optimized pages with meta tags, clean URL structure, and sitemap",
      "Responsive design optimized for mobile, tablet, and desktop",
      "Secure contact and project inquiry forms with spam protection",
      "Blog / News section for sharing agency updates, design insights, and case studies",
    ],
  },

  {
    id: 4,
    slug: "eden-distribution",
    title: "Eden Distribution – FMCG Distributor in Madagascar",
    description:
      "Eden Distribution is a Madagascan company specializing in the supply of a wide range of fast-moving consumer goods (FMCG) to the market.",
    thumbnail: "/projects/eden-distribution/thumb.png",
    screenshots: [
      "/projects/eden-distribution/1.png",
      "/projects/eden-distribution/2.png",
      "/projects/eden-distribution/3.png",
      "/projects/eden-distribution/4.png",
      "/projects/eden-distribution/5.png",
    ],
    link: "https://edens.mg",
    tags: ["Next.js", "Tailwind CSS", "Typescript", "Framer Motion"],
    category: "Website / Distribution Company",
    status: "Live",
    created: "2025-11-28",
    updated: "2025-11-28",
    contributors: 1,
    views: 0,
    progress: 100,
    funFact:
      "Eden Distribution employs around 100 people and runs distribution centers in Antananarivo and Toamasina, with a planned expansion to Réunion.",
    features: [
      "Online catalogue of FMCG products",
      "Distribution centers in Antananarivo and Toamasina",
      "Plan for expansion to Réunion",
      "Contact form / customer inquiries",
      "Customer testimonials and reviews",
    ],
  },

  {
    id: 5,
    slug: "tombola-manager",
    title: "Tombola Manager – Automated Raffle Application",
    description:
      "A full-stack Next.js application designed to manage company raffles with two separate interfaces (admin and client). Includes separate authentication systems (admin token), Firebase data storage, automated Facebook draw announcements via n8n, Docker containerization, and Jest unit testing. The goal is to provide a simple, accessible (responsive + a11y), and robust experience for managing automated raffle draws.",
    thumbnail: "/projects/tombola-manager/thumb.png",
    screenshots: [
      "/projects/tombola-manager/1.png",
      "/projects/tombola-manager/2.png",
      "/projects/tombola-manager/3.png",
      "/projects/tombola-manager/4.png",
      "/projects/tombola-manager/5.png",
      "/projects/tombola-manager/6.png",
      "/projects/tombola-manager/7.png",
      "/projects/tombola-manager/8.png",
      "/projects/tombola-manager/9.png",
    ],
    link: "https://tombola.edens.mg",
    tags: [
      "Next.js",
      "Tailwind CSS",
      "Typescript",
      "Firebase",
      "Docker",
      "n8n",
      "Jest",
    ],
    category: "Application / Raffle System",
    status: "Completed",
    created: "2025-11-28",
    updated: "2025-11-28",
    contributors: 1,
    views: 0,
    progress: 100,
    funFact:
      "The draw results are automatically posted to Facebook using n8n, with a clean separation between admin and client accounts for enhanced security.",
    features: [
      "Admin dashboard: draw management, participants, automation, and settings",
      "Client interface: ticket purchase, participation, and draw viewing",
      "Separated authentication (admin token) with role management",
      "Firebase-based data storage and real-time sync",
      "Automated Facebook draw announcements via n8n",
      "Docker containerization for reproducible deployments",
      "Jest unit testing to ensure robustness",
      "Responsive design and adherence to accessibility best practices",
      "Simple UX with transparent draw processes",
    ],
  },

  {
    id: 6,
    slug: "financial-edu-mobile-app",
    title: "Mobile Financial Education Application – Union of the Comoros",
    description:
      "A lightweight and accessible mobile application designed to teach financial education to rural women, artisans, farmers, merchants, and small businesses in the Comoros. The app provides simple lessons, quizzes, financial calculators, progress tracking, and optional community features. It is available offline and built with modern web technologies for cross-platform usage.",
    thumbnail: "/projects/msomo-wa-mali/thumb.png",
    screenshots: [
      "/projects/msomo-wa-mali/1.gif",
      "/projects/msomo-wa-mali/2.png",
      "/projects/msomo-wa-mali/3.png",
      "/projects/msomo-wa-mali/4.png",
      "/projects/msomo-wa-mali/5.png",
      "/projects/msomo-wa-mali/6.png",
      "/projects/msomo-wa-mali/7.png",
      "/projects/msomo-wa-mali/8.png",
      "/projects/msomo-wa-mali/9.png",
      "/projects/msomo-wa-mali/10.png",
      "/projects/msomo-wa-mali/11.png",
      "/projects/msomo-wa-mali/12.png",
    ],
    link: "https://drive.google.com/file/d/1WnkJENlZg340R2Dn8uOym1Y4X-l4QMHf/view?usp=drive_link",
    tags: [
      "Next.js",
      "React Native",
      "Expo",
      "Firebase",
      "Typescript",
      "Tailwind CSS",
    ],
    category: "Mobile Application / Educational Platform",
    status: "In Progress",
    created: "2025-05-04",
    updated: "2025-05-04",
    contributors: 2,
    views: 0,
    progress: 75,
    funFact:
      "The application is designed to work fully offline so that rural populations with limited connectivity can still benefit from financial education.",
    features: [
      "Short thematic financial lessons with text, images, and audio",
      "Educational quizzes and mini-games with scoring",
      "Simple financial calculators (budget, savings, credit simulators)",
      "Push notifications and learning reminders",
      "User progression tracking, badges, and downloadable PDF certificates",
      "Community forum with basic Q&A and comments",
      "User dashboard showing completed modules and progress",
      "Optional back-office for content management",
      "Multilingual support planned for version 2",
      "Mobile-first modern UI with local illustrations",
    ],
    techStack: {
      frontend: "Nuxt.js (Web), React Native (Mobile)",
      mobileWrapper: "Capacitor for APK generation",
      backend: "Firebase or Supabase (Auth, Database, File Storage)",
      languages: ["TypeScript", "JavaScript"],
    },
    modulesEstimation: [
      { module: "Learning Modules", days: 6, cost_ar: 1000000 },
      { module: "Quizzes & Educational Games", days: 4, cost_ar: 1000000 },
      { module: "Financial Calculators", days: 4, cost_ar: 750000 },
      { module: "Notifications & Reminders", days: 3, cost_ar: 500000 },
      { module: "Progress Tracking", days: 5, cost_ar: 500000 },
      { module: "Community Forum", days: 6, cost_ar: 750000 },
      { module: "User Dashboard", days: 4, cost_ar: 500000 },
      { module: "Back-office (optional)", days: 5, cost_ar: 500000 },
      { module: "Multilingual (v2)", days: 3, cost_ar: 500000 },
      { module: "Graphics/UI Integration", days: 5, cost_ar: 500000 },
    ],
    budget: {
      total_ar: 6500000,
      playStoreFee_eur: 25,
      maintenance_ar_per_month: "200000–500000",
      hosting: "Firebase free tier or up to 25 €/month",
    },
    deliverables: [
      "Android APK (Play Store + direct download)",
      "Responsive web application (PWA)",
      "Documented source code",
      "User manual (PDF, FR)",
      "Admin manual (if back-office included)",
    ],
    deployment: [
      "Play Store account creation (client)",
      "APK signing using Capacitor or Android Studio",
      "Play Store publishing: product page, screenshots, category",
      "Direct APK download available via website or QR code",
    ],
    testingPlan: [
      "Field testing with at least 5 sample users",
      "UI/UX adjustments based on feedback",
      "Technical tests: offline mode, APK size, performance",
      "1-month post-delivery warranty",
      "Future improvements: multilingual, audio/video courses, support chat",
    ],
    duration: {
      developmentDays: 45,
      totalTime: "6 weeks and 3 days with 2 developers",
      testingAndAdjustments: "Additional 2 weeks",
    },
  },

  {
    id: 7,
    slug: "tri-company-admin-dashboard",
    title: "Multi-Company Admin Dashboard (3-in-1 System)",
    description:
      "A unified admin dashboard designed to manage three different companies using the same application base. The system handles product distribution operations (PPN and cosmetics) for supermarkets and retail shops, with real-time data integration.",
    thumbnail: "/projects/dashboard/thumb.png",
    screenshots: [
      "/projects/dashboard/1.png",
      "/projects/dashboard/2.png",
      "/projects/dashboard/3.png",
      // "/projects/dashboard/4.png",
    ],
    link: "#",
    tags: [
      "Next.js",
      "Tailwind CSS",
      "SQL Server",
      // "Sage Compta",
      "Socket.io",
      "Typescript",
      "n8n",
    ],
    category: "Enterprise Management System",
    status: "Completed",
    created: "2024-02-28",
    updated: "2024-02-28",
    contributors: 1,
    views: 1450,
    progress: 100,
    funFact:
      "The system allows all three companies to share the same core application while keeping their data and operations fully isolated.",
    features: [
      "Multi-company architecture (3 systems in 1)",
      "Real-time stock and sales updates via Socket.io",
      "Integration with SQL Server and Sage Compta",
      "Product distribution workflow management",
      "Advanced role and permission management",
      "Dashboard analytics for each company",
      "Invoice and transaction monitoring",
    ],
  },
];
